import React, { useEffect, useState, useCallback } from 'react';
import { SidePanel } from '@ohif/ui-next';
import { Types, utils } from '@ohif/core';

const { getUrlParams } = utils;

export type SidePanelWithServicesProps = {
  servicesManager: AppTypes.ServicesManager;
  side: 'left' | 'right';
  className?: string;
  activeTabIndex: number;
  tabs: any;
  expandedWidth?: number;
  isMobile?: boolean;
};

// Custom Xpectria panel that needs more room than the default 248px panel
// width to be usable (rich text report editor). Widened only while it's the
// active tab so every other panel/mode keeps the standard width.
const WIDE_PANEL_IDS = ['@ohif/extension-measurement-tracking.panelModule.report'];
const WIDE_PANEL_WIDTH = 680;

// The "Historial" tab lets a user browse a patient's other studies/reports
// across sedes. Links generated by "Compartir estudio" only carry
// view_report (no view_measurements) so they stay scoped to the single
// shared study - hide the tab entirely rather than just blocking its
// content, since its mere presence would hint at more studies existing.
const HISTORY_PANEL_ID = '@ohif/extension-measurement-tracking.panelModule.history';

const canViewPatientHistory = (): boolean => {
  try {
    return getUrlParams().permissions?.view_measurements ?? true;
  } catch {
    // Fail open: don't break panel rendering for contexts without the
    // Xpectria "id" url param (e.g. modes/dev setups outside that flow).
    return true;
  }
};

const filterPanelsByPermission = tabs => {
  if (canViewPatientHistory()) {
    return tabs;
  }
  return tabs.filter(tab => tab.id !== HISTORY_PANEL_ID);
};

const SidePanelWithServices = ({
  servicesManager,
  side,
  activeTabIndex: activeTabIndexProp,
  tabs: tabsProp,
  expandedWidth,
  ...props
}: SidePanelWithServicesProps) => {
  const panelService = servicesManager?.services?.panelService;

  // Tracks whether this SidePanel has been opened at least once since this SidePanel was inserted into the DOM.
  // Thus going to the Study List page and back to the viewer resets this flag for a SidePanel.
  const [sidePanelOpen, setSidePanelOpen] = useState(activeTabIndexProp !== null);
  const [activeTabIndex, setActiveTabIndex] = useState(activeTabIndexProp);
  const [tabs, setTabs] = useState(
    filterPanelsByPermission(tabsProp ?? panelService.getPanels(side))
  );

  const handleActiveTabIndexChange = useCallback(({ activeTabIndex }) => {
    setActiveTabIndex(activeTabIndex);
    setSidePanelOpen(activeTabIndex !== null);
  }, []);

  const handleOpen = useCallback(() => {
    setSidePanelOpen(true);
    // If panel is being opened but no tab is active, set first tab as active
    if (activeTabIndex === null && tabs.length > 0) {
      setActiveTabIndex(0);
    }
  }, [activeTabIndex, tabs]);

  const handleClose = useCallback(() => {
    setSidePanelOpen(false);
    setActiveTabIndex(null);
  }, []);

  /** update the active tab index from outside */
  useEffect(() => {
    setActiveTabIndex(activeTabIndexProp);
  }, [activeTabIndexProp]);

  useEffect(() => {
    const { unsubscribe } = panelService.subscribe(
      panelService.EVENTS.PANELS_CHANGED,
      panelChangedEvent => {
        if (panelChangedEvent.position !== side) {
          return;
        }

        setTabs(filterPanelsByPermission(panelService.getPanels(side)));
      }
    );

    return () => {
      unsubscribe();
    };
  }, [panelService, side]);

  useEffect(() => {
    const activatePanelSubscription = panelService.subscribe(
      panelService.EVENTS.ACTIVATE_PANEL,
      (activatePanelEvent: Types.ActivatePanelEvent) => {
        if (sidePanelOpen || activatePanelEvent.forceActive) {
          const tabIndex = tabs.findIndex(tab => tab.id === activatePanelEvent.panelId);
          if (tabIndex !== -1) {
            setActiveTabIndex(tabIndex);
          }
        }
      }
    );

    return () => {
      activatePanelSubscription.unsubscribe();
    };
  }, [tabs, sidePanelOpen, panelService]);

  const activeTab = activeTabIndex !== null ? tabs[activeTabIndex] : null;
  const computedExpandedWidth = WIDE_PANEL_IDS.includes(activeTab?.id)
    ? WIDE_PANEL_WIDTH
    : expandedWidth;

  return (
    <SidePanel
      {...props}
      side={side}
      tabs={tabs}
      activeTabIndex={activeTabIndex}
      onOpen={handleOpen}
      onClose={handleClose}
      onActiveTabIndexChange={handleActiveTabIndexChange}
      expandedWidth={computedExpandedWidth}
    />
  );
};

export default SidePanelWithServices;
